### ISSUE TITLE
Bug: Animated gif embeds do not show up

### ISSUE THREAD

**Issue by StormyDragon** [StormyDragon/TwitFix#12]
I have noticed some gif tweets not working, but not sure whether they worked before (but they work with normal twitter.com links, and seem to work with other forks)
An example: https://ayytwitter.com/Tangeluscious/status/1533257180379549697 [technically sfw, but mature]

_Originally posted by @Deer-Spangle in https://github.com/StormyDragon/TwitFix/issues/9#issuecomment-1146813526_

**Comment by StormyDragon** [comment]
Turns out that the bitrate selection had another bug in that animated gifs have bitrate 0 and would not initialize the video link.

**Comment by Deer-Spangle** [comment]
Thanks again!
