### ISSUE TITLE
Failed to scan links

### ISSUE THREAD

**Issue by guninvalid** [StormyDragon/TwitFix#18]
ayytwitter hasn't been working on Discord for a couple days now. Every link I try, including links that should otherwise work and get through Discord, complains of Failed to scan link. Is ayytwitter down or something?

**Comment by guninvalid** [comment]
![image](https://github.com/StormyDragon/TwitFix/assets/28638276/f2e4f1eb-f3d1-4613-b91a-ce6a6152e30a)

**Comment by StormyDragon** [comment]
I've let the software coast for a while now. I have no interest in perpetuating peoples reliance on Twitter through this system, it was ostensibly meant to be a tool for fixing issues with displaying tweets on other sites but with the shuttering of the free API my options for continuing maintenance becomes a fight with the twitter developers and the clown at the top. I'm certainly not paying them for API access, nor will I go and scrape the website like everyone else is doing now.

Thank you for your interest in helping though, I appreciate it very much.
